version: '3.8'

name: shennas-studio-coolify

services:
  # Medusa Backend API
  medusa-backend:
    build:
      context: ./ocean-backend
      dockerfile: Dockerfile
    container_name: shennas-medusa-backend
    restart: unless-stopped
    ports:
      - "9000:9000"    # API
      - "7001:7001"    # Admin Panel
# Environment variables will be managed by Coolify
    volumes:
      - medusa_uploads:/app/uploads
      - medusa_static:/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - coolify

  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shennas-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
# Environment variables will be managed by Coolify
    depends_on:
      medusa-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - coolify

# Named Volumes (no database volumes needed since using external DBs)
volumes:
  medusa_uploads:
    driver: local
  medusa_static:
    driver: local

# Networks
networks:
  coolify:
    external: true