# Self-contained deployment for Coolify VPS
name: shennas-studio-coolify

services:
  # PostgreSQL Database - embedded in the stack
  postgres:
    image: postgres:15-alpine
    container_name: shennas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ocean_store
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: medusa_secure_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medusa_user -d ocean_store"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - coolify
    # Internal port only - no external exposure needed
    expose:
      - "5432"

  # Redis Cache - embedded in the stack
  redis:
    image: redis:7-alpine
    container_name: shennas-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - coolify
    # Internal port only - no external exposure needed
    expose:
      - "6379"

  # Medusa Backend API - with auto database setup
  medusa-backend:
    build:
      context: ./ocean-backend
      dockerfile: Dockerfile
    container_name: shennas-medusa-backend
    restart: unless-stopped
    ports:
      - "9000:9000"    # API
      - "7001:7001"    # Admin Panel
    environment:
      # Database - using internal container network
      - DATABASE_URL=postgresql://medusa_user:medusa_secure_password_2024@postgres:5432/ocean_store
      - REDIS_URL=redis://redis:6379
      
      # Security
      - NODE_ENV=production
      - JWT_SECRET=Ip/YHC0sc5jJ14zB+XUuA/V9mOrRujTE8YvqySCEK3cQUhLQWhFvF6MDmg5VTJ+W
      - COOKIE_SECRET=cLwStjcBgDkBAAHhHT0rbC3LDg9fN2hgz6X+VHjnKreVDfo8qGhm618k0EkRwdsL
      
      # CORS Configuration for production
      - STORE_CORS=https://shennasstudio.com,https://www.shennasstudio.com,http://localhost:3000
      - ADMIN_CORS=https://admin.shennasstudio.com,http://localhost:7001
      - AUTH_CORS=https://shennasstudio.com,https://www.shennasstudio.com,http://localhost:3000
      
      # Auto-initialize database
      - AUTO_INITIALIZE_DB=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - medusa_uploads:/app/uploads
      - medusa_static:/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
    networks:
      - coolify

  # Next.js Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shennas-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Backend Connection
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://medusa-backend:9000
      
      # App Configuration
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    depends_on:
      medusa-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - coolify

# Named Volumes
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  medusa_uploads:
    driver: local
  medusa_static:
    driver: local

# Networks
networks:
  coolify:
    driver: bridge