[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "npm install sharp --legacy-peer-deps"
]

[phases.build]
cmds = [
  "chmod +x pre-build.sh",
  "bash pre-build.sh",
  "cp .env.railway .env.production.local",
  "cat .env.production.local",
  "npm run build"
]
# Make environment variables available during build
dependsOn = ["install"]

[variables]
# Ensure NEXT_PUBLIC_* variables are available during build
NODE_ENV = "production"

[start]
cmd = "bash railway-start.sh"
