version: '3.8'

name: shennas-studio

services:
  redis:
    image: redis:7-alpine
    container_name: shennas-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  medusa-backend:
    build:
      context: ./ocean-backend
      dockerfile: Dockerfile
    container_name: shennas-medusa-backend
    restart: unless-stopped
    ports:
      - "9000:9000"    # API
      - "7001:7001"    # Admin UI (if that’s configured)
    environment:
      - NODE_ENV=production

      # Database
      - DATABASE_URL=${DATABASE_URL}               # must supply from external Supabase
      - DATABASE_SSL=${DATABASE_SSL:-true}         # possibly "true"
      - DATABASE_SSL_REJECT_UNAUTHORIZED=${DATABASE_SSL_REJECT_UNAUTHORIZED:-true}

      # Redis
      - REDIS_URL=redis://redis:6379

      # Security
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}

      # CORS
      - STORE_CORS=${STORE_CORS:-*}
      - ADMIN_CORS=${ADMIN_CORS:-*}
      - AUTH_CORS=${AUTH_CORS:-*}

      # Admin setup
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@shennastudio.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-AdminPassword123!}

      # Auto init
      - AUTO_MIGRATE=${AUTO_MIGRATE:-true}
      - AUTO_SEED=${AUTO_SEED:-false}
      - AUTO_CREATE_ADMIN=${AUTO_CREATE_ADMIN:-true}

      # Medusa config flags (if used in your version)
      - MEDUSA_ADMIN_ONBOARDING_TYPE=default
      - MEDUSA_ADMIN_ONBOARDING_NEXTJS=true
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - medusa_uploads:/app/uploads
      - medusa_static:/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]   # or /health if available
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shennas-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_MEDUSA_BACKEND_URL=${NEXT_PUBLIC_MEDUSA_BACKEND_URL:-http://medusa-backend:9000}
      # Other frontend envs you need
    depends_on:
      medusa-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

volumes:
  redis_data:
  medusa_uploads:
  medusa_static:

networks:
  default:
    name: shennas-network
    driver: bridge
