name: shennas-studio

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: shennas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: shennas_studio_db
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: medusa_secure_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medusa_user -d shennas_studio_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: shennas-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # Medusa Backend API
  medusa-backend:
    build:
      context: ./ocean-backend
      dockerfile: Dockerfile
    container_name: shennas-medusa-backend
    restart: unless-stopped
    ports:
      - "9000:9000"    # API
      - "7001:7001"    # Admin Panel
    environment:
      # Database
      - DATABASE_URL=postgresql://medusa_user:medusa_secure_password_2024@postgres:5432/shennas_studio_db
      - REDIS_URL=redis://redis:6379
      
      # Security
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-super-secure-jwt-secret-minimum-32-characters-change-in-production}
      - COOKIE_SECRET=${COOKIE_SECRET:-your-super-secure-cookie-secret-minimum-32-characters-change-in-production}
      
      # CORS Configuration
      - STORE_CORS=${STORE_CORS:-http://localhost:3000,https://shennastudio.com,https://www.shennastudio.com}
      - ADMIN_CORS=${ADMIN_CORS:-http://localhost:7001,https://admin.shennastudio.com}
      - AUTH_CORS=${AUTH_CORS:-http://localhost:3000,https://shennastudio.com,https://www.shennastudio.com}
      
      # Admin Setup
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@shennastudio.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-ChangeThisPassword123!}
      
      # Auto-initialization
      - AUTO_MIGRATE=true
      - AUTO_SEED=true
      - AUTO_CREATE_ADMIN=true
      
      # Medusa Configuration
      - MEDUSA_ADMIN_ONBOARDING_TYPE=default
      - MEDUSA_ADMIN_ONBOARDING_NEXTJS=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - medusa_uploads:/app/uploads
      - medusa_static:/app/static
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s



# Named Volumes
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  medusa_uploads:
    driver: local
  medusa_static:
    driver: local

# Networks
networks:
  default:
    name: shennas-network
    driver: bridge