[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps || npm install",
  "cd ocean-backend && npm ci --legacy-peer-deps || npm install"
]

[phases.build]
cmds = [
  "npm run build",
  "cd ocean-backend && npx --yes @medusajs/cli@latest build"
]

[start]
cmd = "./railway-start.sh"
