[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "cp -r public .next/standalone/",
  "cp -r .next/static .next/standalone/.next/"
]

[start]
cmd = "node .next/standalone/server.js"

[[ports]]
port = "3000"
protocol = "tcp"

[variables]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"
NEXT_TELEMETRY_DISABLED = "1"