[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci",
  "npm install -g pm2"
]

[phases.build]
cmds = [
  "npm run build",
  "cp -r public .next/standalone/",
  "cp -r .next/static .next/standalone/.next/",
  "mkdir -p logs"
]

[start]
cmd = "pm2-runtime start ecosystem.config.js"

[[ports]]
port = "3000"
protocol = "tcp"

[variables]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"
NEXT_TELEMETRY_DISABLED = "1"