[phases.setup]
nixPkgs = ["nodejs_20", "curl"]

[phases.install]
cmds = [
  "npm ci --include=dev",
  "npm install -g pm2"
]

[phases.build]
cmds = [
  "npm run build",
  "mkdir -p logs"
]

[start]
cmd = "npx medusa db:migrate && pm2-runtime start ecosystem.config.js"

[[ports]]
port = "9000"
protocol = "tcp"

[healthcheck]
test = ["CMD", "curl", "-f", "http://localhost:9000/health"]
interval = "30s"
timeout = "10s"
retries = 5
start_period = "180s"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--experimental-vm-modules"
PORT = "9000"