[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --include=dev",
  "npm install -g pm2"
]

[phases.build]
cmds = [
  "npm run build",
  "npx medusa migrations run || echo 'Migrations will run at startup'",
  "mkdir -p logs"
]

[start]
cmd = "npx medusa migrations run && pm2-runtime start ecosystem.config.js"

[[ports]]
port = "9000"
protocol = "tcp"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--experimental-vm-modules"
PORT = "9000"