[phases.setup]
nixPkgs = ["nodejs_20", "npm", "python3"]

[phases.install]
cmds = [
  "npm ci --omit=dev --ignore-scripts"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "9000"

[build]
ignoredPaths = [
  "src/scripts/create-auth.ts",
  "src/scripts/fix-password.ts",
  "src/scripts/create-working-admin.ts",
  "src/scripts/create-publishable-key.ts",
  "src/scripts/reset-admin.ts"
]