[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = [
  "npm run build",
  "npx medusa migrations run"
]

[start]
cmd = "npm start"

[[ports]]
port = "9000"
protocol = "tcp"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--experimental-vm-modules"
PORT = "9000"