[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd .medusa/server && npm install --omit=dev && npx medusa db:migrate && node index.js"

[variables]
NODE_ENV = "production"
PORT = "9000"
DATABASE_TYPE = "postgres"
MEDUSA_BACKEND_URL = "{{MEDUSA_BACKEND_URL}}"
MEDUSA_ADMIN_URL = "{{MEDUSA_ADMIN_URL}}"
STORE_CORS = "{{STORE_CORS}}"
ADMIN_CORS = "{{ADMIN_CORS}}"
AUTH_CORS = "{{AUTH_CORS}}"
DATABASE_URL = "{{DATABASE_URL}}"
REDIS_URL = "{{REDIS_URL}}"
JWT_SECRET = "{{JWT_SECRET}}"
COOKIE_SECRET = "{{COOKIE_SECRET}}"
ADMIN_EMAIL = "{{ADMIN_EMAIL}}"
ADMIN_PASSWORD = "{{ADMIN_PASSWORD}}"
